### ISSUE TITLE
"error":{"message":"The Content-MD5 you specified did not match what we received.","co de"

### ISSUE THREAD

**Issue by teebu** [matt-filion/s3-db#15]
```
var test_file_1 = JSON.parse(fs.readFileSync(`./test/${file}`, 'utf8'));
database.getCollection('mydb')
  .then( collection => collection.saveDocument(test_file_1) )
  .catch( error => console.error(error) )
```

```
{ BadDigest: The Content-MD5 you specified did not match what we received.
    at Request.extractError (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\services\s3.js:568:35)
    at Request.callListeners (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\request.js:682:14)
    at Request.transition (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\request.js:684:12)
    at Request.callListeners (C:\Users\hello\Documents\Learning\Lambdas\s3db\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'The Content-MD5 you specified did not match what we received.',
  code: 'BadDigest',
  region: null,
  time: 2017-06-17T18:07:56.232Z,
  requestId: '1D886C49334CF1FB',
  extendedRequestId: 'ql+U0UE7ZjXqyGhW/9gDK/cGWifNvOBqrTP6DglYjhXc9TmYs3RhF600+t9KktZquRlR+KceauE=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 74.86007695144244 }

Process finished with exit code 0

```

**Comment by teebu** [comment]
I think I ran into your serialize bug. 

Using your default serializer fixes the issue. 

```
serializer: {
    serialize: data => JSON.stringify(data),
    deserialize: data => JSON.parse(data)
  }
```

**Comment by matt-filion** [comment]
I'll see if I can find a better resolution. So you have the 100k file that
causes the failure? It would help me create a reliable solution.

**Comment by teebu** [comment]
I'm not sure if the size is the issue. Here is the file:
[1176522123.gz](https://github.com/matt-filion/s3-db/files/1082711/1176522123.gz)

**Comment by teebu** [comment]
I think i found the bug. It wasn't the signature, it was the length.

```
putDocument: (request) => {
        const params = {
          Bucket: bucketName(request.fqn),
          Key: getId(request.fqn,request.id),
          ContentType: 'application/json',
          ContentLength: getBytes(request.body),
          Body: request.body,
          ContentMD5: Utils.signature(request.body)
        };

        function getBytes(string){
          return Buffer.byteLength(string, 'utf8')
        }
```

**Comment by teebu** [comment]
https://github.com/matt-filion/s3-db/pull/16

**Comment by teebu** [comment]
with this you probably don't need to do your escape encoding

**Comment by matt-filion** [comment]
I found some scenarios with single quotes in the values were resulting in the outputs not matching. I'm not sure that character counts will address those scenarios but I'll try and dig up some examples and test it out. I had a long thread with AWS about the issue.

**Comment by matt-filion** [comment]
I was able to verify today that this does resolve it the serialization issue I was seeing before. Thanks for this contribution!
